#server:
#  port: 8080
#eureka:
#  instance:
#    hostname: localhost
#    port: 9091
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#ribbon:
#  eureka:
#    enabled: true
##logging:
##  level:
##    ROOT: INFO
##    org.springframework.web: DEBUG
#zuul:
#  host:
#    connect-timeout-millis: 150000
#    connection-request-timeout-millis: 150000
#  sensitive-headers: Cookie,Set-Cookie
#  ignored-patterns: /actuator/routes/**
#  routes:
#    oauth:
#      path: /**
#      service-id: SERVER-OAUTH
#    beneficiario:
#      path: /api/beneficiarios/**
#      service-id: SERVICE-BENEFICIARIO