server:
  port: 9091
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    non-secure-port: 80
  client:
    fetch-registry: false
    register-with-eureka: true
    prefer-same-zone-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000