server:
  port: 9093
eureka:
  instance:
    hostname: localhost
    port: 9091
    prefer-ip-address: true
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: portal
    platform: oracle
    url: ##############
    username: portal
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
authserver:
  hostname: http://localhost:8080
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user