server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: http://bitbucket.unimedfortaleza.com.br/scm/wpm/configs
          username: portal
          password: p0rt4l